### ISSUE TITLE
Feedback wrote-javascript-to-avoid-javascript

### ISSUE THREAD

**Issue by GrosSacASac** [markentier/markentier.tech#25]
_Writing here since email is not listed in the about page_

I am working on a blog engine with similar ideas in mind, avoiding JS on the client side: [Blog-engine-sac](https://gitlab.com/GrosSacASac/blog-engine-z)
The only JS client side is for the search bar (client side instant search)

For the pictures I use it differently:
`
```html
<picture class="position-relative">
    <source srcset="/images/${name}.jpg" media="(min-width: 2000px)">
    <source srcset="/images/${name}-${standard}.jpg" media="(min-width: 992px)">
    <img alt="" src="/images/${name}-${small}.jpg" class="w100 hauto">
</picture>`
````

This will load the full resolution image only for big screens, the regular version for medium screens and the low resolution for small screens

Why is posthtml-align-style inside vendor instead of node_modules ?

**Comment by asaaki** [comment]
Thank you for your feedback. 💙

Pictures:
I haven't spent extra time yet on media break points.
With AVIF eventually being available on all major browser also not being a pressing topic to me.
I usually build my post images with a width of 1024px and let it scale, and with the compression  of WEBP and AVIF the files are decently small enough for most users. People on larger screen might suffer a bit due to not having higher resolutions available for them. I will regret that myself in 10 years probably. 😅

Vendored packages:
- `posthtml-img-autosize` is a copy and has a tiny fix for skipping SVGs, I haven't bothered to get it upstream yet. Should do it soon.
- `posthtml-align-style` and `posthtml-avif-webp` are my own creations to quickly adjust the tree as I need it.

For the latter 2 I maybe plan to fully open source them as individual packages, but then again, my day also has only 24 hours and I have to choose how to spend them. If there is an interest, I might feel more intrigued to do so. 😉

Blog engine / static site generator:
Such an idea is also lingering around, but similar to professional work I'm too lazy and pragmatic to invest too much time in it. Current setup does work for the most parts and I feel not too annoyed by the things not working well enough yet.
Writing a blog engine is a lot of work, more than one would initially image.
I definitely wish you the best for your project! May you be more motivated and energized than I am. 😄
